# Generated by Django 2.2.5 on 2021-02-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajadorModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=250)),
                ('uadscripcion', models.CharField(max_length=250)),
                ('telefono', models.CharField(max_length=70)),
                ('correo', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=12)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
