# Generated by Django 2.2.5 on 2021-02-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20210216_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajadormodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='trabajadormodel',
            name='verificado',
        ),
        migrations.AddField(
            model_name='trabajadormodel',
            name='verificar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trabajadormodel',
            name='categoria',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='trabajadormodel',
            name='correo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='trabajadormodel',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trabajadormodel',
            name='nombre',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='trabajadormodel',
            name='telefono',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trabajadormodel',
            name='turno',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='trabajadormodel',
            name='uadscripcion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
